"""initial schema

Revision ID: 433c9d5ee8f1
Revises: 
Create Date: 2026-07-19 11:45:00.112306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433c9d5ee8f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_period', sa.String(), nullable=False),
    sa.Column('form', sa.String(), nullable=False),
    sa.Column('accession_number', sa.String(), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Numeric(), nullable=True),
    sa.Column('net_income', sa.Numeric(), nullable=True),
    sa.Column('market_cap', sa.Numeric(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('taxonomy', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'fiscal_year', 'fiscal_period', 'accession_number', name='uq_fundamental_period_filing')
    )
    with op.batch_alter_table('fundamentals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fundamentals_ticker'), ['ticker'], unique=False)

    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'as_of', name='uq_price_ticker_date')
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prices_ticker'), ['ticker'], unique=False)

    op.create_table('refresh_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('tickers_attempted', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('failures', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticker_ciks',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('tickers',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sub_sector', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    with op.batch_alter_table('tickers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickers_sub_sector'), ['sub_sector'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickers_sub_sector'))

    op.drop_table('tickers')
    op.drop_table('ticker_ciks')
    op.drop_table('refresh_logs')
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prices_ticker'))

    op.drop_table('prices')
    with op.batch_alter_table('fundamentals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fundamentals_ticker'))

    op.drop_table('fundamentals')
    # ### end Alembic commands ###
